{-# OPTIONS --safe #-}
module FreeGpd.Base where

open import Prelude

private variable
  ℓv ℓe ℓ ℓ′ : Level
  V : 𝒰 ℓv
  A : 𝒰 ℓ
  G : V → V → 𝒰 ℓe
  H : A → A → 𝒰 ℓ′

-- free 1-groupoid generated by a graph
-- aka geometric realization

data FreeGpd (G : V → V → 𝒰 ℓe) : 𝒰 (level-of-type V ⊔ ℓe) where
  vtx   : V → FreeGpd G
  edge  : {x y : V} → G x y → vtx x ＝ vtx y
  trunc : is-groupoid (FreeGpd G)

elim : {C : FreeGpd G → 𝒰 ℓ}
     → is-of-hlevel-dep 2 C
     → (vc : (v : V) → C (vtx v))
     → ({x y : V} → (e : G x y) → ＜ vc x ／ (λ i → C (edge {x = x} {y = y} e i)) ＼ vc y ＞)
     → (fg : FreeGpd G) → C fg
elim gp vc ec (vtx v)                   = vc v
elim gp vc ec (edge e i)                = ec e i
elim gp vc ec (trunc p q u v x y i j k) =
  gp (go p) (go q)
     (λ h → go (u h))
     (λ h → go (v h))
     (λ h k → go (x h k))
     (λ h k → go (y h k))
     (trunc p q u v x y)
     i j k
  where go = elim gp vc ec

elim-set : {C : FreeGpd G → 𝒰 ℓ}
         → (∀ fg → is-set (C fg))
         → (vc : (v : V) → C (vtx v))
         → ({x y : V} → (e : G x y) → ＜ vc x ／ (λ i → C (edge {x = x} {y = y} e i)) ＼ vc y ＞)
         → (fg : FreeGpd G) → C fg
elim-set sc =
  elim λ {a₀} {a₁} →
      is-of-hlevel→is-of-hlevel-dep 2
            (λ q → is-of-hlevel-suc 2 (sc q))
          {a₀} {a₁}

elim-prop : {C : FreeGpd G → 𝒰 ℓ}
          → (∀ fg → is-prop (C fg))
          → (vc : (v : V) → C (vtx v))
          → (fg : FreeGpd G) → C fg
elim-prop pc vc =
  elim
    (    λ {a₀} {a₁} →
      is-of-hlevel→is-of-hlevel-dep 2
            (λ q → is-of-hlevel-+ 1 2 (pc q))
          {a₀} {a₁})
    vc
    (λ e → to-pathᴾ (pc (edge e i1) _ (vc _)))

rec : is-groupoid A
    → (va : V → A)
    → ({x y : V} → G x y → va x ＝ va y)
    → FreeGpd G → A
rec gp va vc (vtx v)                   = va v
rec gp va vc (edge e i)                = vc e i
rec gp va vc (trunc p q u v x y i j k) =
  gp (go p) (go q)
     (λ h → go (u h))
     (λ h → go (v h))
     (λ h k → go (x h k))
     (λ h k → go (y h k))
     i j k
  where go = rec gp va vc

-- mapping a graph homomorphism
map-hom : (f : V → A)
        → ({x y : V} → G x y → H (f x) (f y))
        → FreeGpd G → FreeGpd H
map-hom f g = rec trunc (vtx ∘ f) (edge ∘ g)
